[HW-6] Add installation guide to `README.md` file
AlexLevshenkov/LifoContainers pull request #31
Opened 2024-05-25 00:27 UTC by AlexLevshenkov

## List of changes

- **Build `.xcframework` by yourself** section has been transformed to **Installation Guide**

2024-05-25 17:17 UTC, Nikitapls requested changes
PTAL at unresolved conversations

2024-05-25 17:17 UTC, Nikitapls commented on README.md
> +
I would suggest you to add the note about minimum versions to this section and remove it from the original place.
```suggestion

**Warning** `LifoContainers` supports SPM from `0.2.0` version.
```

2024-05-25 17:17 UTC, Nikitapls commented on README.md
> +### XCFrameworks
nit:
```suggestion
### XCFramework
```

2024-05-25 17:17 UTC, Nikitapls commented on README.md
> +Each [release](https://github.com/AlexLevshenkov/LifoContainers/releases) includes `*.xcframework` framework binaries.
nit:
```suggestion
Each [release](https://github.com/AlexLevshenkov/LifoContainers/releases) includes `*.xcframework` framework binary.
```

2024-05-25 17:17 UTC, Nikitapls commented on README.md
> +4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button
I would add a note that in most cases user should choose the `Do not embed` option.
```suggestion
4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button. We recommend you to choose the `Do not embed` option.
```

2024-05-25 17:17 UTC, Nikitapls commented on README.md
> +4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button
```suggestion
4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button.
```

2024-05-25 17:30 UTC, auhustsinovich requested changes
please consider following improvements:

2024-05-25 17:30 UTC, auhustsinovich commented on README.md
> +The [Swift Package Manager](https://swift.org/package-manager/) is a tool for automating the distribution of Swift code and is integrated into the `swift` compiler. `LifoContainers` supports SPM from
nit: I can see only `0.1.0` version of your framework, I think you can add this info after release `0.2.0`. For now it doesn`t make any sense.

2024-05-25 17:30 UTC, auhustsinovich commented on README.md
> +2. Enter "https://github.com/AlexLevshenkov/LifoContainers" into the package repository URL text field;
You have already provided a link to documentation where user can find installation guide, don't teach them how to use Xcode 👀 

```suggestion
You can add `LifoContainers` to an Xcode project by [adding it as a package dependency](https://developer.apple.com/documentation/xcode/adding-package-dependencies-to-your-app#Add-a-package-dependency).
```

2024-05-25 17:30 UTC, auhustsinovich commented on README.md
> +Once you have your Swift package set up, adding `LifoContainers` as a dependency is as easy as adding it to the `dependencies` value of your `Package.swift`:
I'm a little confused, do I have to create a swift package file or not? If not, make it explicit that it's an option to choose to either install through Xcode or through the file directly.

2024-05-26 11:55 UTC, AlexLevshenkov commented on README.md
> +### XCFrameworks
Section has been renamed

2024-05-26 11:55 UTC, AlexLevshenkov commented on README.md
> +Each [release](https://github.com/AlexLevshenkov/LifoContainers/releases) includes `*.xcframework` framework binaries.
Your suggestion has been applied

2024-05-26 11:55 UTC, AlexLevshenkov commented on README.md
> +Once you have your Swift package set up, adding `LifoContainers` as a dependency is as easy as adding it to the `dependencies` value of your `Package.swift`:
If you want to use `LifoContainers` in your own custom framework(with SPM support) this is the way how to integrate my framework into your framework.

2024-05-26 11:55 UTC, AlexLevshenkov commented on README.md
> +2. Enter "https://github.com/AlexLevshenkov/LifoContainers" into the package repository URL text field;
I don't 🙂. The documentation is broader, and I added 2 actions exactly for my Swift package. The user can quickly connect the framework via the 2 moves, or go deeper inside the Apple documentation, then search somewhere for the link to the my git repository which is inconvenient.

2024-05-26 11:55 UTC, AlexLevshenkov commented on README.md
> +4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button
The user actually shouldn't choose, it is only his decision how he is going to connect the framework.

2024-05-26 11:55 UTC, AlexLevshenkov commented on README.md
> +4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button
This peace of text has been refactored

2024-05-26 12:30 UTC, Nikitapls commented on README.md
> +4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button
We agreed that this is a nit, I leave this up to you.

2024-05-26 12:30 UTC, Nikitapls approved these changes
LGTM

2024-05-26 17:20 UTC, AlexLevshenkov commented on README.md
> +4. Add the framework target to the **Frameworks, Libraries, and Embedded Content** section by clicking the **Add(+)** button
I have added some text regarding it

2024-05-26 17:23 UTC, AlexLevshenkov commented on README.md
> +The [Swift Package Manager](https://swift.org/package-manager/) is a tool for automating the distribution of Swift code and is integrated into the `swift` compiler. `LifoContainers` supports SPM from
The plan is to create tag `0.2.0` and then the release after this PR is merged to let users see the installation guide when they switch to `0.2.0` tag.

2024-05-27 12:44 UTC, auhustsinovich approved these changes
LGTM

2024-05-27 12:46 UTC, merged

2024-05-27 12:46 UTC, AlexLevshenkov commented
The pull request had been reviewed and then approved. All conversations were resolved. Merged