[HW-8] Setup GitHub actions
AlexLevshenkov/LifoContainers pull request #40
Opened 2024-07-01 11:08 UTC by AlexLevshenkov

The pull request **MUST** be merged **AFTER**:
- #38 

## List of changes

- workflow for the pull requests has been created;
- there are 2 stages in the created workflow: code style check and running tests for the project

2024-07-01 19:03 UTC, Nikitapls commented on .github/workflows/pull-request-workflow.yml
> +                sh ./scripts/run-linters.sh
I'd suggest splitting this into two separate steps because you are changing permissions for your script.

```suggestion
            - name: Add execution permission to the run-linters.sh
              run: chmod +x ./scripts/run-linters.sh
            - name: Linting
              run: sh ./scripts/run-linters.sh
```

2024-07-01 22:36 UTC, AlexLevshenkov commented on .github/workflows/pull-request-workflow.yml
> +                sh ./scripts/run-linters.sh
I don't really think adding permissions to execute the script is a different step cause these two commands are super connected to each other.

2024-07-01 22:37 UTC, AlexLevshenkov commented on LifoContainers/LifoContainers/Stacks/StackStatistics.swift
> +    /// Keeps minimum elements in the stack.
The unexpected changes have been deleted

2024-07-02 06:10 UTC, Nikitapls commented on .github/workflows/pull-request-workflow.yml
> +                sh ./scripts/run-linters.sh
I'm concerned that your step is named `Linting`, but inside it, you're changing permissions for your script and linting the sources. I'd suggest using my example or changing the step name to the `Set Permissions and Linting` to explain that you are changing permissions too.

2024-07-02 08:51 UTC, AlexLevshenkov commented on .github/workflows/pull-request-workflow.yml
> +                sh ./scripts/run-linters.sh
The step has been renamed

2024-07-02 11:48 UTC, Shadowman405 approved these changes

2024-07-02 17:28 UTC, Nikitapls approved these changes
LGTM

2024-07-02 20:54 UTC, dersim-davaod requested changes
Consider improvements from the https://github.com/AlexLevshenkov/ios-engineering-school-hws/pull/77

2024-07-02 20:54 UTC, dersim-davaod commented on .github/workflows/pull-request-workflow.yml
> +                sh ./scripts/run-linters.sh
Why do you run the script with the `sh`?
Could you please explain why not:
```bash
./scripts/run-linters.sh
```
?

2024-07-05 19:06 UTC, AlexLevshenkov commented on .github/workflows/pull-request-workflow.yml
> +                sh ./scripts/run-linters.sh
I have removed `sh`.

2024-07-08 11:47 UTC, dersim-davaod requested changes
Consider minor improvements of readability.
Take a look at suggestion from https://github.com/AlexLevshenkov/ios-engineering-school-hws/pull/77

2024-07-08 11:47 UTC, dersim-davaod commented on .github/workflows/pull-request-any.yml
> +      - name: add-x-permission-and-execute-run-linters-sh
nit:
```suggestion
      - run-linters-as-a-script
```

2024-07-08 11:47 UTC, dersim-davaod commented on .github/workflows/pull-request-any.yml
> +      - name: search-for-cache
nit:
```suggestion
      - name: search-for-cached-brew-formulaes
```

2024-07-08 16:14 UTC, AlexLevshenkov commented on .github/workflows/pull-request-any.yml
> +      - name: search-for-cache
I have changed the name of the step

2024-07-08 16:14 UTC, AlexLevshenkov commented on .github/workflows/pull-request-any.yml
> +      - name: add-x-permission-and-execute-run-linters-sh
I have changed the name of the step

2024-07-11 20:48 UTC, dersim-davaod approved these changes
LGTM

2024-07-11 20:51 UTC, dersim-davaod commented on .github/workflows/pull-request-checks.yml
> +name: pull-request-checks
nit: The name of the workflow isn't clear. As I said please consider applying advice from the https://github.com/AlexLevshenkov/ios-engineering-school-hws/pull/77

2024-07-11 20:53 UTC, AlexLevshenkov commented on .github/workflows/pull-request-checks.yml
> +name: pull-request-checks
@dersim-davaod I didn't find the name describing 2 operations: code style check and tests execution. So I chose "generic" one

2024-07-11 21:38 UTC, AlexLevshenkov commented on .github/workflows/pull-request-checks.yml
> +name: pull-request-checks
@dersim-davaod I have renamed the workflow, PTAL

2024-07-12 19:01 UTC, dersim-davaod approved these changes
LGTM

2024-07-12 19:02 UTC, merged

2024-07-12 19:03 UTC, AlexLevshenkov commented
The pull request had been reviewed and then approved. All conversations were resolved. Merged